FROM node:14.15.0
USER root
RUN npm config set registry https://registry.npm.taobao.org
RUN yarn config set registry https://registry.npm.taobao.org/
RUN yarn global add @vue/cli @vue/cli-service-global
